package db

import (
	"database/sql"
	"errors"
	"fmt"
	"strings"

	_ "github.com/jackc/pgx/v5/stdlib"
)

func Open(dsn string, autoMigrate bool) (*sql.DB, error) {
	trimmed := strings.TrimSpace(dsn)
	if trimmed == "" {
		return nil, errors.New("PostgreSQL DSN 未配置")
	}
	database, err := sql.Open("pgx", trimmed)
	if err != nil {
		return nil, err
	}
	if err := database.Ping(); err != nil {
		database.Close()
		return nil, err
	}
	if autoMigrate {
		if err := migrate(database); err != nil {
			database.Close()
			return nil, err
		}
	}
	return database, nil
}

func migrate(database *sql.DB) error {
	statements := []string{
		`CREATE TABLE IF NOT EXISTS backtest_sessions (
			id varchar(36) PRIMARY KEY,
			token_address varchar(128) NOT NULL,
			token_symbol varchar(64) NOT NULL DEFAULT '',
			"interval" varchar(32) NOT NULL,
			start_time timestamptz NOT NULL,
			end_time timestamptz NOT NULL,
			created_at timestamptz,
			updated_at timestamptz
		)`,
		`CREATE INDEX IF NOT EXISTS idx_backtest_sessions_token_address ON backtest_sessions (token_address)`,
		`CREATE INDEX IF NOT EXISTS idx_backtest_sessions_start_time ON backtest_sessions (start_time)`,
		`CREATE INDEX IF NOT EXISTS idx_backtest_sessions_end_time ON backtest_sessions (end_time)`,
		`CREATE TABLE IF NOT EXISTS backtest_trade_points (
			id varchar(36) PRIMARY KEY,
			session_id varchar(36) NOT NULL,
			side varchar(16) NOT NULL,
			point_time timestamptz NOT NULL,
			input_price double precision,
			note varchar(512) NOT NULL DEFAULT '',
			matched_kline_time timestamptz,
			matched_price double precision,
			created_at timestamptz
		)`,
		`CREATE INDEX IF NOT EXISTS idx_backtest_trade_points_session_id ON backtest_trade_points (session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_backtest_trade_points_point_time ON backtest_trade_points (point_time)`,
		`CREATE TABLE IF NOT EXISTS backtest_trade_results (
			id varchar(36) PRIMARY KEY,
			session_id varchar(36) NOT NULL,
			buy_point_id varchar(36) NOT NULL,
			sell_point_id varchar(36) NOT NULL,
			buy_matched_kline_time timestamptz NOT NULL,
			sell_matched_kline_time timestamptz NOT NULL,
			buy_price double precision NOT NULL,
			sell_price double precision NOT NULL,
			profit double precision NOT NULL,
			profit_rate double precision NOT NULL,
			holding_seconds bigint NOT NULL,
			win boolean NOT NULL,
			created_at timestamptz
		)`,
		`CREATE INDEX IF NOT EXISTS idx_backtest_trade_results_session_id ON backtest_trade_results (session_id)`,
		`CREATE TABLE IF NOT EXISTS backtest_metric_snapshots (
			id varchar(36) PRIMARY KEY,
			session_id varchar(36) NOT NULL UNIQUE,
			trade_count bigint NOT NULL,
			win_rate double precision NOT NULL,
			total_profit_rate double precision NOT NULL,
			max_drawdown_rate double precision NOT NULL,
			average_holding_seconds bigint NOT NULL,
			created_at timestamptz
		)`,
		`CREATE TABLE IF NOT EXISTS birdeye_kline_cache (
			token_address varchar(128) NOT NULL,
			"interval" varchar(32) NOT NULL,
			open_time timestamptz NOT NULL,
			close_time timestamptz NOT NULL,
			market_cap_open double precision NOT NULL,
			market_cap_high double precision NOT NULL,
			market_cap_low double precision NOT NULL,
			market_cap_close double precision NOT NULL,
			volume double precision NOT NULL,
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL,
			PRIMARY KEY (token_address, "interval", open_time)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_birdeye_kline_cache_token_interval_open_time ON birdeye_kline_cache (token_address, "interval", open_time)`,
		`CREATE TABLE IF NOT EXISTS birdeye_kline_cache_ranges (
			token_address varchar(128) NOT NULL,
			"interval" varchar(32) NOT NULL,
			range_start timestamptz NOT NULL,
			range_end timestamptz NOT NULL,
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL,
			PRIMARY KEY (token_address, "interval", range_start, range_end)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_birdeye_kline_cache_ranges_lookup ON birdeye_kline_cache_ranges (token_address, "interval", range_start, range_end)`,
		`CREATE TABLE IF NOT EXISTS system_kline_cache (
			token_address varchar(128) NOT NULL,
			"interval" varchar(32) NOT NULL,
			open_time timestamptz NOT NULL,
			close_time timestamptz NOT NULL,
			open_price double precision NOT NULL,
			high_price double precision NOT NULL,
			low_price double precision NOT NULL,
			close_price double precision NOT NULL,
			market_cap_open double precision NOT NULL,
			market_cap_high double precision NOT NULL,
			market_cap_low double precision NOT NULL,
			market_cap_close double precision NOT NULL,
			volume double precision NOT NULL,
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL,
			PRIMARY KEY (token_address, "interval", open_time)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_system_kline_cache_token_interval_open_time ON system_kline_cache (token_address, "interval", open_time)`,
		`CREATE TABLE IF NOT EXISTS system_kline_cache_ranges (
			token_address varchar(128) NOT NULL,
			"interval" varchar(32) NOT NULL,
			range_start timestamptz NOT NULL,
			range_end timestamptz NOT NULL,
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL,
			PRIMARY KEY (token_address, "interval")
		)`,
		`CREATE INDEX IF NOT EXISTS idx_system_kline_cache_ranges_lookup ON system_kline_cache_ranges (token_address, "interval", range_start, range_end)`,
		`CREATE TABLE IF NOT EXISTS system_runtime_settings (
			setting_key varchar(64) PRIMARY KEY,
			setting_value text NOT NULL,
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS trade_accounts (
			id varchar(36) PRIMARY KEY,
			name varchar(64) NOT NULL UNIQUE,
			wallet_address varchar(128) NOT NULL,
			status varchar(16) NOT NULL,
			buy_amount_usd double precision NOT NULL,
			slippage_bps integer NOT NULL,
			priority_fee_lamports bigint NOT NULL,
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS trade_signals (
			id varchar(36) PRIMARY KEY,
			signal_id varchar(96) NOT NULL UNIQUE,
			signal_type varchar(16) NOT NULL,
			strategy_code varchar(64) NOT NULL,
			token_address varchar(128) NOT NULL,
			"interval" varchar(32) NOT NULL,
			signal_time timestamptz NOT NULL,
			trigger_price double precision NOT NULL,
			trigger_market_cap double precision NOT NULL,
			reason text NOT NULL,
			raw_payload_json jsonb NOT NULL,
			consume_status varchar(16) NOT NULL,
			created_at timestamptz NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_trade_signals_token_address ON trade_signals (token_address)`,
		`CREATE INDEX IF NOT EXISTS idx_trade_signals_signal_time ON trade_signals (signal_time DESC)`,
		`ALTER TABLE trade_signals ADD COLUMN IF NOT EXISTS trade_mode varchar(16)`,
		`UPDATE trade_signals SET trade_mode = 'live' WHERE COALESCE(trade_mode, '') = ''`,
		`ALTER TABLE trade_signals ALTER COLUMN trade_mode SET NOT NULL`,
		`CREATE TABLE IF NOT EXISTS trade_orders (
			id varchar(36) PRIMARY KEY,
			account_id varchar(36) NOT NULL,
			signal_id varchar(36) NOT NULL,
			token_address varchar(128) NOT NULL,
			side varchar(16) NOT NULL,
			intent_amount_usd double precision NOT NULL,
			intent_token_amount double precision NOT NULL,
			status varchar(24) NOT NULL,
			jupiter_request_json jsonb,
			jupiter_response_json jsonb,
			submit_tx_hash varchar(128) NOT NULL DEFAULT '',
			confirmed_at timestamptz,
			fail_reason text NOT NULL DEFAULT '',
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_trade_orders_account_created_at ON trade_orders (account_id, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_trade_orders_signal_id ON trade_orders (signal_id)`,
		`ALTER TABLE trade_orders ADD COLUMN IF NOT EXISTS trade_mode varchar(16)`,
		`ALTER TABLE trade_orders ADD COLUMN IF NOT EXISTS execution_channel varchar(32)`,
		`UPDATE trade_orders SET trade_mode = 'live' WHERE COALESCE(trade_mode, '') = ''`,
		`UPDATE trade_orders SET execution_channel = 'jupiter_live' WHERE COALESCE(execution_channel, '') = ''`,
		`ALTER TABLE trade_orders ALTER COLUMN trade_mode SET NOT NULL`,
		`ALTER TABLE trade_orders ALTER COLUMN execution_channel SET NOT NULL`,
		`CREATE TABLE IF NOT EXISTS trade_fills (
			id varchar(36) PRIMARY KEY,
			order_id varchar(36) NOT NULL,
			tx_hash varchar(128) NOT NULL,
			side varchar(16) NOT NULL,
			token_address varchar(128) NOT NULL,
			filled_token_amount double precision NOT NULL,
			filled_quote_amount double precision NOT NULL,
			avg_price double precision NOT NULL,
			fee_amount double precision NOT NULL,
			fee_asset varchar(32) NOT NULL,
			executed_at timestamptz NOT NULL,
			created_at timestamptz NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_trade_fills_order_id ON trade_fills (order_id)`,
		`ALTER TABLE trade_fills ADD COLUMN IF NOT EXISTS trade_mode varchar(16)`,
		`ALTER TABLE trade_fills ADD COLUMN IF NOT EXISTS is_simulated boolean`,
		`UPDATE trade_fills SET trade_mode = 'live' WHERE COALESCE(trade_mode, '') = ''`,
		`UPDATE trade_fills SET is_simulated = false WHERE is_simulated IS NULL`,
		`ALTER TABLE trade_fills ALTER COLUMN trade_mode SET NOT NULL`,
		`ALTER TABLE trade_fills ALTER COLUMN is_simulated SET NOT NULL`,
		`CREATE TABLE IF NOT EXISTS trade_positions (
			id varchar(36) PRIMARY KEY,
			account_id varchar(36) NOT NULL,
			token_address varchar(128) NOT NULL,
			status varchar(16) NOT NULL,
			open_order_id varchar(36) NOT NULL,
			close_order_id varchar(36) NOT NULL DEFAULT '',
			quantity double precision NOT NULL,
			cost_amount double precision NOT NULL,
			avg_cost_price double precision NOT NULL,
			last_price double precision NOT NULL,
			market_value double precision NOT NULL,
			realized_pnl double precision NOT NULL,
			unrealized_pnl double precision NOT NULL,
			max_profit_rate double precision NOT NULL,
			max_drawdown_amount double precision NOT NULL,
			opened_at timestamptz NOT NULL,
			closed_at timestamptz,
			updated_at timestamptz NOT NULL
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_trade_positions_account_token_open ON trade_positions (account_id, token_address) WHERE status = 'open'`,
		`CREATE INDEX IF NOT EXISTS idx_trade_positions_status_updated_at ON trade_positions (status, updated_at DESC)`,
		`ALTER TABLE trade_positions ADD COLUMN IF NOT EXISTS trade_mode varchar(16)`,
		`UPDATE trade_positions SET trade_mode = 'live' WHERE COALESCE(trade_mode, '') = ''`,
		`ALTER TABLE trade_positions ALTER COLUMN trade_mode SET NOT NULL`,
		`CREATE TABLE IF NOT EXISTS trade_order_events (
			id varchar(36) PRIMARY KEY,
			order_id varchar(36) NOT NULL,
			event_type varchar(32) NOT NULL,
			event_time timestamptz NOT NULL,
			detail_json jsonb NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_trade_order_events_order_time ON trade_order_events (order_id, event_time DESC)`,
		`CREATE TABLE IF NOT EXISTS birdeye_api_keys (
			id varchar(36) PRIMARY KEY,
			api_key text NOT NULL UNIQUE,
			key_mask varchar(32) NOT NULL,
			status varchar(16) NOT NULL,
			unavailable_reason text NOT NULL DEFAULT '',
			unavailable_at timestamptz,
			last_successful_used_at timestamptz,
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_birdeye_api_keys_status_created_at ON birdeye_api_keys (status, created_at ASC)`,
		`CREATE TABLE IF NOT EXISTS gmgn_api_keys (
			id varchar(36) PRIMARY KEY,
			api_key text NOT NULL UNIQUE,
			key_mask varchar(32) NOT NULL,
			status varchar(16) NOT NULL,
			unavailable_reason text NOT NULL DEFAULT '',
			unavailable_at timestamptz,
			last_successful_used_at timestamptz,
			created_at timestamptz NOT NULL,
			updated_at timestamptz NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_gmgn_api_keys_status_created_at ON gmgn_api_keys (status, created_at ASC)`,
	}
	statements = append(statements, commentStatements()...)
	for _, statement := range statements {
		if _, err := database.Exec(statement); err != nil {
			return fmt.Errorf("migrate postgres failed: %w", err)
		}
	}
	return nil
}

func commentStatements() []string {
	return []string{
		`COMMENT ON TABLE backtest_sessions IS '回测分析会话表'`,
		`COMMENT ON COLUMN backtest_sessions.id IS '回测会话ID'`,
		`COMMENT ON COLUMN backtest_sessions.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN backtest_sessions.token_symbol IS 'Token符号'`,
		`COMMENT ON COLUMN backtest_sessions."interval" IS 'K线周期'`,
		`COMMENT ON COLUMN backtest_sessions.start_time IS '回测开始时间'`,
		`COMMENT ON COLUMN backtest_sessions.end_time IS '回测结束时间'`,
		`COMMENT ON COLUMN backtest_sessions.created_at IS '创建时间'`,
		`COMMENT ON COLUMN backtest_sessions.updated_at IS '更新时间'`,
		`COMMENT ON TABLE backtest_trade_points IS '回测输入买卖点表'`,
		`COMMENT ON COLUMN backtest_trade_points.id IS '买卖点ID'`,
		`COMMENT ON COLUMN backtest_trade_points.session_id IS '回测会话ID'`,
		`COMMENT ON COLUMN backtest_trade_points.side IS '买卖方向'`,
		`COMMENT ON COLUMN backtest_trade_points.point_time IS '输入点位时间'`,
		`COMMENT ON COLUMN backtest_trade_points.input_price IS '输入价格'`,
		`COMMENT ON COLUMN backtest_trade_points.note IS '备注'`,
		`COMMENT ON COLUMN backtest_trade_points.matched_kline_time IS '匹配K线时间'`,
		`COMMENT ON COLUMN backtest_trade_points.matched_price IS '匹配价格'`,
		`COMMENT ON COLUMN backtest_trade_points.created_at IS '创建时间'`,
		`COMMENT ON TABLE backtest_trade_results IS '回测逐笔交易结果表'`,
		`COMMENT ON COLUMN backtest_trade_results.id IS '交易结果ID'`,
		`COMMENT ON COLUMN backtest_trade_results.session_id IS '回测会话ID'`,
		`COMMENT ON COLUMN backtest_trade_results.buy_point_id IS '买入点ID'`,
		`COMMENT ON COLUMN backtest_trade_results.sell_point_id IS '卖出点ID'`,
		`COMMENT ON COLUMN backtest_trade_results.buy_matched_kline_time IS '买入匹配K线时间'`,
		`COMMENT ON COLUMN backtest_trade_results.sell_matched_kline_time IS '卖出匹配K线时间'`,
		`COMMENT ON COLUMN backtest_trade_results.buy_price IS '买入价格'`,
		`COMMENT ON COLUMN backtest_trade_results.sell_price IS '卖出价格'`,
		`COMMENT ON COLUMN backtest_trade_results.profit IS '收益金额'`,
		`COMMENT ON COLUMN backtest_trade_results.profit_rate IS '收益率'`,
		`COMMENT ON COLUMN backtest_trade_results.holding_seconds IS '持仓秒数'`,
		`COMMENT ON COLUMN backtest_trade_results.win IS '是否盈利'`,
		`COMMENT ON COLUMN backtest_trade_results.created_at IS '创建时间'`,
		`COMMENT ON TABLE backtest_metric_snapshots IS '回测指标快照表'`,
		`COMMENT ON COLUMN backtest_metric_snapshots.id IS '指标快照ID'`,
		`COMMENT ON COLUMN backtest_metric_snapshots.session_id IS '回测会话ID'`,
		`COMMENT ON COLUMN backtest_metric_snapshots.trade_count IS '交易次数'`,
		`COMMENT ON COLUMN backtest_metric_snapshots.win_rate IS '胜率'`,
		`COMMENT ON COLUMN backtest_metric_snapshots.total_profit_rate IS '总收益率'`,
		`COMMENT ON COLUMN backtest_metric_snapshots.max_drawdown_rate IS '最大回撤率'`,
		`COMMENT ON COLUMN backtest_metric_snapshots.average_holding_seconds IS '平均持仓秒数'`,
		`COMMENT ON COLUMN backtest_metric_snapshots.created_at IS '创建时间'`,
		`COMMENT ON TABLE birdeye_kline_cache IS 'Birdeye K线缓存表'`,
		`COMMENT ON COLUMN birdeye_kline_cache.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN birdeye_kline_cache."interval" IS 'K线周期'`,
		`COMMENT ON COLUMN birdeye_kline_cache.open_time IS 'K线开盘时间'`,
		`COMMENT ON COLUMN birdeye_kline_cache.close_time IS 'K线收盘时间'`,
		`COMMENT ON COLUMN birdeye_kline_cache.market_cap_open IS '开盘市值'`,
		`COMMENT ON COLUMN birdeye_kline_cache.market_cap_high IS '最高市值'`,
		`COMMENT ON COLUMN birdeye_kline_cache.market_cap_low IS '最低市值'`,
		`COMMENT ON COLUMN birdeye_kline_cache.market_cap_close IS '收盘市值'`,
		`COMMENT ON COLUMN birdeye_kline_cache.volume IS '成交量'`,
		`COMMENT ON COLUMN birdeye_kline_cache.created_at IS '创建时间'`,
		`COMMENT ON COLUMN birdeye_kline_cache.updated_at IS '更新时间'`,
		`COMMENT ON TABLE birdeye_kline_cache_ranges IS 'Birdeye K线缓存覆盖区间表'`,
		`COMMENT ON COLUMN birdeye_kline_cache_ranges.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN birdeye_kline_cache_ranges."interval" IS 'K线周期'`,
		`COMMENT ON COLUMN birdeye_kline_cache_ranges.range_start IS '缓存区间开始时间'`,
		`COMMENT ON COLUMN birdeye_kline_cache_ranges.range_end IS '缓存区间结束时间'`,
		`COMMENT ON COLUMN birdeye_kline_cache_ranges.created_at IS '创建时间'`,
		`COMMENT ON COLUMN birdeye_kline_cache_ranges.updated_at IS '更新时间'`,
		`COMMENT ON TABLE system_kline_cache IS '系统自维护K线缓存表'`,
		`COMMENT ON COLUMN system_kline_cache.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN system_kline_cache."interval" IS 'K线周期'`,
		`COMMENT ON COLUMN system_kline_cache.open_time IS 'K线开盘时间'`,
		`COMMENT ON COLUMN system_kline_cache.close_time IS 'K线收盘时间'`,
		`COMMENT ON COLUMN system_kline_cache.open_price IS '外部返回开盘价格'`,
		`COMMENT ON COLUMN system_kline_cache.high_price IS '外部返回最高价格'`,
		`COMMENT ON COLUMN system_kline_cache.low_price IS '外部返回最低价格'`,
		`COMMENT ON COLUMN system_kline_cache.close_price IS '外部返回收盘价格'`,
		`COMMENT ON COLUMN system_kline_cache.market_cap_open IS '开盘市值'`,
		`COMMENT ON COLUMN system_kline_cache.market_cap_high IS '最高市值'`,
		`COMMENT ON COLUMN system_kline_cache.market_cap_low IS '最低市值'`,
		`COMMENT ON COLUMN system_kline_cache.market_cap_close IS '收盘市值'`,
		`COMMENT ON COLUMN system_kline_cache.volume IS '成交量'`,
		`COMMENT ON COLUMN system_kline_cache.created_at IS '创建时间'`,
		`COMMENT ON COLUMN system_kline_cache.updated_at IS '更新时间'`,
		`COMMENT ON TABLE system_kline_cache_ranges IS '系统K线缓存覆盖区间表'`,
		`COMMENT ON COLUMN system_kline_cache_ranges.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN system_kline_cache_ranges."interval" IS 'K线周期'`,
		`COMMENT ON COLUMN system_kline_cache_ranges.range_start IS '缓存区间开始时间'`,
		`COMMENT ON COLUMN system_kline_cache_ranges.range_end IS '缓存区间结束时间'`,
		`COMMENT ON COLUMN system_kline_cache_ranges.created_at IS '创建时间'`,
		`COMMENT ON COLUMN system_kline_cache_ranges.updated_at IS '更新时间'`,
		`COMMENT ON TABLE system_runtime_settings IS '系统运行时配置表'`,
		`COMMENT ON COLUMN system_runtime_settings.setting_key IS '配置键'`,
		`COMMENT ON COLUMN system_runtime_settings.setting_value IS '配置值'`,
		`COMMENT ON COLUMN system_runtime_settings.created_at IS '创建时间'`,
		`COMMENT ON COLUMN system_runtime_settings.updated_at IS '更新时间'`,
		`COMMENT ON TABLE trade_accounts IS '交易账户表'`,
		`COMMENT ON COLUMN trade_accounts.id IS '账户ID'`,
		`COMMENT ON COLUMN trade_accounts.name IS '账户名称'`,
		`COMMENT ON COLUMN trade_accounts.wallet_address IS '钱包地址'`,
		`COMMENT ON COLUMN trade_accounts.status IS '账户状态'`,
		`COMMENT ON COLUMN trade_accounts.buy_amount_usd IS '单次买入金额USD'`,
		`COMMENT ON COLUMN trade_accounts.slippage_bps IS '滑点基点'`,
		`COMMENT ON COLUMN trade_accounts.priority_fee_lamports IS '优先费lamports'`,
		`COMMENT ON COLUMN trade_accounts.created_at IS '创建时间'`,
		`COMMENT ON COLUMN trade_accounts.updated_at IS '更新时间'`,
		`COMMENT ON TABLE trade_signals IS '交易信号表'`,
		`COMMENT ON COLUMN trade_signals.id IS '内部信号ID'`,
		`COMMENT ON COLUMN trade_signals.signal_id IS '外部信号ID'`,
		`COMMENT ON COLUMN trade_signals.trade_mode IS '交易模式'`,
		`COMMENT ON COLUMN trade_signals.signal_type IS '信号方向'`,
		`COMMENT ON COLUMN trade_signals.strategy_code IS '策略编码'`,
		`COMMENT ON COLUMN trade_signals.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN trade_signals."interval" IS 'K线周期'`,
		`COMMENT ON COLUMN trade_signals.signal_time IS '信号时间'`,
		`COMMENT ON COLUMN trade_signals.trigger_price IS '触发价格'`,
		`COMMENT ON COLUMN trade_signals.trigger_market_cap IS '触发市值'`,
		`COMMENT ON COLUMN trade_signals.reason IS '触发原因'`,
		`COMMENT ON COLUMN trade_signals.raw_payload_json IS '原始信号JSON'`,
		`COMMENT ON COLUMN trade_signals.consume_status IS '消费状态'`,
		`COMMENT ON COLUMN trade_signals.created_at IS '创建时间'`,
		`COMMENT ON TABLE trade_orders IS '交易订单表'`,
		`COMMENT ON COLUMN trade_orders.id IS '订单ID'`,
		`COMMENT ON COLUMN trade_orders.account_id IS '账户ID'`,
		`COMMENT ON COLUMN trade_orders.signal_id IS '内部信号ID'`,
		`COMMENT ON COLUMN trade_orders.trade_mode IS '交易模式'`,
		`COMMENT ON COLUMN trade_orders.execution_channel IS '执行通道'`,
		`COMMENT ON COLUMN trade_orders.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN trade_orders.side IS '买卖方向'`,
		`COMMENT ON COLUMN trade_orders.intent_amount_usd IS '意图金额USD'`,
		`COMMENT ON COLUMN trade_orders.intent_token_amount IS '意图Token数量'`,
		`COMMENT ON COLUMN trade_orders.status IS '订单状态'`,
		`COMMENT ON COLUMN trade_orders.jupiter_request_json IS 'Jupiter请求JSON'`,
		`COMMENT ON COLUMN trade_orders.jupiter_response_json IS 'Jupiter响应JSON'`,
		`COMMENT ON COLUMN trade_orders.submit_tx_hash IS '提交交易哈希'`,
		`COMMENT ON COLUMN trade_orders.confirmed_at IS '确认时间'`,
		`COMMENT ON COLUMN trade_orders.fail_reason IS '失败原因'`,
		`COMMENT ON COLUMN trade_orders.created_at IS '创建时间'`,
		`COMMENT ON COLUMN trade_orders.updated_at IS '更新时间'`,
		`COMMENT ON TABLE trade_fills IS '交易成交表'`,
		`COMMENT ON COLUMN trade_fills.id IS '成交ID'`,
		`COMMENT ON COLUMN trade_fills.order_id IS '订单ID'`,
		`COMMENT ON COLUMN trade_fills.trade_mode IS '交易模式'`,
		`COMMENT ON COLUMN trade_fills.is_simulated IS '是否模拟成交'`,
		`COMMENT ON COLUMN trade_fills.tx_hash IS '交易哈希'`,
		`COMMENT ON COLUMN trade_fills.side IS '买卖方向'`,
		`COMMENT ON COLUMN trade_fills.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN trade_fills.filled_token_amount IS '成交Token数量'`,
		`COMMENT ON COLUMN trade_fills.filled_quote_amount IS '成交计价金额'`,
		`COMMENT ON COLUMN trade_fills.avg_price IS '平均成交价'`,
		`COMMENT ON COLUMN trade_fills.fee_amount IS '手续费金额'`,
		`COMMENT ON COLUMN trade_fills.fee_asset IS '手续费资产'`,
		`COMMENT ON COLUMN trade_fills.executed_at IS '成交时间'`,
		`COMMENT ON COLUMN trade_fills.created_at IS '创建时间'`,
		`COMMENT ON TABLE trade_positions IS '交易持仓表'`,
		`COMMENT ON COLUMN trade_positions.id IS '持仓ID'`,
		`COMMENT ON COLUMN trade_positions.account_id IS '账户ID'`,
		`COMMENT ON COLUMN trade_positions.trade_mode IS '交易模式'`,
		`COMMENT ON COLUMN trade_positions.token_address IS 'Token CA地址'`,
		`COMMENT ON COLUMN trade_positions.status IS '持仓状态'`,
		`COMMENT ON COLUMN trade_positions.open_order_id IS '开仓订单ID'`,
		`COMMENT ON COLUMN trade_positions.close_order_id IS '平仓订单ID'`,
		`COMMENT ON COLUMN trade_positions.quantity IS '持仓数量'`,
		`COMMENT ON COLUMN trade_positions.cost_amount IS '成本金额'`,
		`COMMENT ON COLUMN trade_positions.avg_cost_price IS '平均成本价'`,
		`COMMENT ON COLUMN trade_positions.last_price IS '最新价格'`,
		`COMMENT ON COLUMN trade_positions.market_value IS '当前市值'`,
		`COMMENT ON COLUMN trade_positions.realized_pnl IS '已实现盈亏'`,
		`COMMENT ON COLUMN trade_positions.unrealized_pnl IS '未实现盈亏'`,
		`COMMENT ON COLUMN trade_positions.max_profit_rate IS '最大收益率'`,
		`COMMENT ON COLUMN trade_positions.max_drawdown_amount IS '最大回撤金额'`,
		`COMMENT ON COLUMN trade_positions.opened_at IS '开仓时间'`,
		`COMMENT ON COLUMN trade_positions.closed_at IS '平仓时间'`,
		`COMMENT ON COLUMN trade_positions.updated_at IS '更新时间'`,
		`COMMENT ON TABLE trade_order_events IS '交易订单事件表'`,
		`COMMENT ON COLUMN trade_order_events.id IS '事件ID'`,
		`COMMENT ON COLUMN trade_order_events.order_id IS '订单ID'`,
		`COMMENT ON COLUMN trade_order_events.event_type IS '事件类型'`,
		`COMMENT ON COLUMN trade_order_events.event_time IS '事件时间'`,
		`COMMENT ON COLUMN trade_order_events.detail_json IS '事件详情JSON'`,
		`COMMENT ON TABLE birdeye_api_keys IS 'Birdeye API Key池表'`,
		`COMMENT ON COLUMN birdeye_api_keys.id IS 'Key记录ID'`,
		`COMMENT ON COLUMN birdeye_api_keys.api_key IS 'Birdeye API Key密文原值'`,
		`COMMENT ON COLUMN birdeye_api_keys.key_mask IS '脱敏Key展示值'`,
		`COMMENT ON COLUMN birdeye_api_keys.status IS 'Key状态'`,
		`COMMENT ON COLUMN birdeye_api_keys.unavailable_reason IS '不可用原因'`,
		`COMMENT ON COLUMN birdeye_api_keys.unavailable_at IS '标记不可用时间'`,
		`COMMENT ON COLUMN birdeye_api_keys.last_successful_used_at IS '最近成功使用时间'`,
		`COMMENT ON COLUMN birdeye_api_keys.created_at IS '创建时间'`,
		`COMMENT ON COLUMN birdeye_api_keys.updated_at IS '更新时间'`,
		`COMMENT ON TABLE gmgn_api_keys IS 'GMGN API Key池表'`,
		`COMMENT ON COLUMN gmgn_api_keys.id IS 'Key记录ID'`,
		`COMMENT ON COLUMN gmgn_api_keys.api_key IS 'GMGN API Key密文原值'`,
		`COMMENT ON COLUMN gmgn_api_keys.key_mask IS '脱敏Key展示值'`,
		`COMMENT ON COLUMN gmgn_api_keys.status IS 'Key状态'`,
		`COMMENT ON COLUMN gmgn_api_keys.unavailable_reason IS '不可用原因'`,
		`COMMENT ON COLUMN gmgn_api_keys.unavailable_at IS '标记不可用时间'`,
		`COMMENT ON COLUMN gmgn_api_keys.last_successful_used_at IS '最近成功使用时间'`,
		`COMMENT ON COLUMN gmgn_api_keys.created_at IS '创建时间'`,
		`COMMENT ON COLUMN gmgn_api_keys.updated_at IS '更新时间'`,
	}
}
